version: "3.2"

services:
  app:
    build:
      context: ./
      dockerfile: testApp.Dockerfile
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3001:3001"
      - "4000:4000"
    image: prkl-test
    container_name: prkl-test
    environment:
      - NODE_ENV=test

  db:
    image: postgres:12
    container_name: prkl-db-test
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data_test:/data

  e2e:
    container_name: prkl-e2e
    command: dockerize -wait tcp://db:5432 -wait tcp://app:3001 -timeout 60s bash -c "./node_modules/.bin/cypress run --headless -b chrome"
    depends_on: 
      - app
      - db
    environment: 
      - CYPRESS_baseUrl=http://app:3001
      - DOCKERIZE_VERSION=v0.6.1
    build:
      context: ./
      dockerfile: test.Dockerfile
    volumes: 
      - ./results:/results
      - ./e2e/cypress/integration:/e2e/cypress/integration
