version: "3.7"

volumes:
  pg_data:

services:
  client:
    build: ./client
    ports:
      - 3000:3000
      - 30011:30011
    container_name: a7r-client
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_CUSTOM_NODE_ENV=development
    volumes:
      - ./client/src:/usr/src/app/src

  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
      args:
        NODE_ENV: development
        REACT_APP_CUSTOM_NODE_ENV: development
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3001:3001"
    container_name: prkl-dev
    environment:
      - "NODE_ENV=development"
      - "REACT_APP_CUSTOM_NODE_ENV=development"

  algorithm:
    build:
      context: ./algorithm
      dockerfile: dev.Dockerfile
      args:
        NODE_ENV: development
    ports:
      - 3004:3004
    container_name: prkl-algorithm
    volumes:
      - ./algorithm:/usr/src/app/algorithm

  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080

  db:
    image: postgres:12
    container_name: prkl-db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    ports:
      - 5432:5432
