version: "3.7"

volumes:
  pg_data:

services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app/frontend

  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
      args:
        NODE_ENV: development
        REACT_APP_CUSTOM_NODE_ENV: development
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3001:3001"
    container_name: prkl-dev
    environment:
      - "NODE_ENV=development"
      - "REACT_APP_CUSTOM_NODE_ENV=development"
    depends_on:
      - frontend

  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080

  db:
    image: postgres:12
    container_name: prkl-db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    ports:
      - 5432:5432
