version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "3001:3001"
    container_name: prkl-dev
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  test-app:
    build: .
    ports:
      - 3001:3001
    container_name: test-app
    environment:
      - NODE_ENV=test
    depends_on:
      - test-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080

  db:
    image: postgres:12
    container_name: prkl-db
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/data
    ports:
      - 5432:5432

  test-db:
    image: postgres:12
    container_name: test-db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  tests:
    build: ./e2e/
    container_name: prkl-test
    environment:
      - CYPRESS_BASE_URL=http://test-app:3001
    depends_on:
      - test-app
    volumes:
      - ./e2e/cypress:/e2e/cypress
