version: 2.1

orbs:
  dockerhub: circleci/docker@1.0.0

executors:
  test-exec:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  run-tests:
    executor: test-exec
    steps:
      - checkout
      - run: docker-compose run tests
      - store_artifacts:
          path: e2e/cypress/videos
      - store_artifacts:
          path: e2e/cypress/screenshots

workflows:
  build-test-deploy:
    jobs:
      - run-tests

      - dockerhub/publish:
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'staging'
          extra_build_args: '--build-arg PUBLIC_URL=/assembler'
          filters:
            branches:
              only: trunk

      - dockerhub/publish:
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'production'
          extra_build_args: '--build-arg PUBLIC_URL=/assembler'
          filters:
            branches:
              only: master

