version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
workflows:
  build-test-deploy:
    jobs:
      - dockerhub/publish:
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'staging'
          extra_build_args: '--build-arg PUBLIC_URL=/prkl/'
          filters:
            branches:
              only: trunk
      - dockerhub/publish:
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'production'
          extra_build_args: '--build-arg PUBLIC_URL=/prkl/'
          filters:
            branches:
              only: master
      - dockerhub/publish:
          image: $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
          tag: 'testing-tests'
          filters:
            branches:
              only: e2e-tests
          after_checkout:
            - run:
                command: docker-compose -f docker-compose-test.yml up --exit-code-from e2e
